---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-postgres
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 5Gi
